FROM ghcr.io/astral-sh/uv:0.5.5-python3.12-alpine

RUN apk update && \
    apk upgrade && \
    apk add --no-cache ffmpeg && \
    apk add make bash curl

COPY . .

# RUN curl -LsSf https://astral.sh/uv/install.sh | sh

# ENV PATH="/root/.local/bin:$PATH"

RUN uv pip install --system -r pyproject.toml --extra bot

CMD [ "python3", "-u", "bot" ]
