FROM python:3.11

RUN apt update && \
    apt upgrade -y && \
    apt install curl -y

COPY . .

RUN curl -LsSf https://astral.sh/uv/install.sh | sh

ENV PATH="/root/.local/bin:$PATH"

RUN uv pip install --system -r pyproject.toml --extra asr-service

EXPOSE 9090:9090

CMD [ "python3", "-u", "inference_server" ]
